pipeline {
  agent {
    docker {
      image 'aditya28jan2003/jenkins-maven-agent:v1'
      args '--user root -v /var/run/docker.sock:/var/run/docker.sock -v /root/.gitconfig:/root/.gitconfig'
    }
  }
  stages {
    stage('Checkout') {
      steps {
        echo 'Code checked out'
      }
    }
    stage('Build and Test') {
      steps {
        dir('spring-boot-app') {
          sh 'mvn clean package'
        }
      }
    }
    stage('Static Code Analysis') {
      environment {
        SONAR_URL = "http://10.43.134.201:9000"
      }
      steps {
        dir('spring-boot-app') {
          withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {
            sh '''
              mvn sonar:sonar \
              -Dsonar.login=$SONAR_AUTH_TOKEN \
              -Dsonar.host.url=$SONAR_URL
            '''
          }
        }
      }
    }
    stage('Build and Push Docker Image') {
      environment {
        DOCKER_IMAGE = "aditya28jan2003/jenkins-maven-agent:${BUILD_NUMBER}"
      }
      steps {
        dir('spring-boot-app') {
          withCredentials([usernamePassword(
            credentialsId: 'docker-creds',
            usernameVariable: 'DOCKER_USER',
            passwordVariable: 'DOCKER_PASS'
          )]) {
            sh '''
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker build -t ${DOCKER_IMAGE} .
              docker push ${DOCKER_IMAGE}
            '''
          }
        }
      }
    }
    stage('Update Deployment File') {
      environment {
        GIT_REPO_NAME = "Java-Maven-Deployment"
        GIT_USER_NAME = "aditya2003sharma"
      }
      steps {
        withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
          sh """
            git config --global --add safe.directory /var/lib/jenkins/workspace/Java
            git config --global user.email "aditya28jan2003@gmail.com"
            git config --global user.name "Aditya Sharma"
            sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" spring-boot-app-manifests/deployment.yml
            git add spring-boot-app-manifests/deployment.yml
            git commit -m "Update deployment image to version ${BUILD_NUMBER}" || true
            git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME}.git HEAD:main
          """
        }
      }
    }
  }
}
